version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12321:80
  db:
    image: mariadb:latest
    env_file:
      - ".env"
    volumes:
      - rodash_db:/var/lib/mysql

volumes:
  rodash_db:
