"""Absen: Remove cardUid

Revision ID: c97e3e5acefb
Revises: cc87f1e432cf
Create Date: 2023-08-12 07:33:18.398061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c97e3e5acefb'
down_revision = 'cc87f1e432cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absen', schema=None) as batch_op:
        batch_op.drop_column('cardUid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cardUid', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
