"""Absen: Tanggal is Date only

Revision ID: cc87f1e432cf
Revises: 01f92762af41
Create Date: 2023-06-30 19:23:50.446496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc87f1e432cf'
down_revision = '01f92762af41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absen', schema=None) as batch_op:
        batch_op.alter_column('tanggal',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absen', schema=None) as batch_op:
        batch_op.alter_column('tanggal',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
